/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SelecionarFilialRouteImport } from './routes/selecionar-filial'
import { Route as SelecaoServicosRouteImport } from './routes/selecao-servicos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as IndexRouteImport } from './routes/index'

const SelecionarFilialRoute = SelecionarFilialRouteImport.update({
  id: '/selecionar-filial',
  path: '/selecionar-filial',
  getParentRoute: () => rootRouteImport,
} as any)
const SelecaoServicosRoute = SelecaoServicosRouteImport.update({
  id: '/selecao-servicos',
  path: '/selecao-servicos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/selecao-servicos': typeof SelecaoServicosRoute
  '/selecionar-filial': typeof SelecionarFilialRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/selecao-servicos': typeof SelecaoServicosRoute
  '/selecionar-filial': typeof SelecionarFilialRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/selecao-servicos': typeof SelecaoServicosRoute
  '/selecionar-filial': typeof SelecionarFilialRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/financeiro'
    | '/login'
    | '/selecao-servicos'
    | '/selecionar-filial'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/financeiro'
    | '/login'
    | '/selecao-servicos'
    | '/selecionar-filial'
  id:
    | '__root__'
    | '/'
    | '/financeiro'
    | '/login'
    | '/selecao-servicos'
    | '/selecionar-filial'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  SelecaoServicosRoute: typeof SelecaoServicosRoute
  SelecionarFilialRoute: typeof SelecionarFilialRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/selecionar-filial': {
      id: '/selecionar-filial'
      path: '/selecionar-filial'
      fullPath: '/selecionar-filial'
      preLoaderRoute: typeof SelecionarFilialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/selecao-servicos': {
      id: '/selecao-servicos'
      path: '/selecao-servicos'
      fullPath: '/selecao-servicos'
      preLoaderRoute: typeof SelecaoServicosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  SelecaoServicosRoute: SelecaoServicosRoute,
  SelecionarFilialRoute: SelecionarFilialRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
